version: "3.8"

services:
  php:
    container_name: amazingblog_php
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    networks:
      - symfony

  nginx:
    container_name: amazingblog_nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - symfony

  mongo:
    container_name: amazingblog_mongo
    image: mongo:8.0
    restart: always
    volumes:
      - "./docker/mongo/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - symfony

  mongo-express:
    container_name: amazingblog_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - symfony

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  symfony:
    driver: bridge
